spring:
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false